[emacs*]
leftalt = layer(alt)
leftmeta = layer(meta)
rightalt = layer(altgr)
rightmeta = layer(meta)
leftcontrol = layer(control)
rightcontrol = layer(control)

[org-gnome-ptyxis*]
meta_mac.t = C-S-t
meta_mac.p = A-p
meta_mac.n = A-n

[google-chrome*]
control.f = right
control.b = left
control.p = up
control.n = down
control.a = home
control.e = end
control.d = delete
control.h = backspace 
control.k = macro(S-end C-x)

[slack]
control.f = right
control.b = left
control.p = up
control.n = down
control.a = home
control.e = end
control.d = delete
control.h = backspace 
control.k = macro(S-end C-x)
