[tools]
deno = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
helm = "latest"
krew = "latest"
kubectl = "latest"
node = "24.17"
oc = { version = "latest", bin = "oc", platforms = { linux-arm64 = { url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version }}/openshift-client-linux-arm64-{{ version }}.tar.gz" }, linux-x64 = { url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version }}/openshift-client-linux-{{ version }}.tar.gz" }, macos-arm64 = { url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version }}/openshift-client-mac-arm64-{{ version }}.tar.gz" }, macos-x64 = { url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version }}/openshift-client-mac-{{ version }}.tar.gz" }, windows-x64 = { url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ version }}/openshift-client-windows-{{ version }}.zip" } }, version_expr = "sortVersions(versions)", version_list_url = "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/", version_regex = 'href="(\d+\.\d+\.\d+)/"' }
peco = "latest"
python = "3.14"
rust = "latest"
stern = "latest"

[tasks.rust-alternatives]
description = "Show Rust Alternatives"
run = """
cat <<END
cat	: bat
diff	: delta
mtr	: ttl
top	: btm
httpie	: xh
dig	: dog
du	: ds, pdu
git	: gitui
xd	: hexyl
ps	: procs
markdown: glow
END
"""
